SELECT * FROM data LIMIT 5;


-- Q1 What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM data
GROUP BY gender;

-- Q2 which customer used a discount but still spent more than average purchase amount?
 SELECT customer_id , purchase_amount
 FROM data
 WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM data);
 
 -- Q3 which are the top 5 products with the highest average review rating?
 SELECT item_purchased , ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) as avg_review_rating 
 from data
 GROUP BY item_purchased
 ORDER BY avg_review_rating DESC
 LIMIT 5;
 
 -- Q4 Compare the average purchase amount between standards and express shipping.
 SELECT  shipping_type, ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS avg_purchase_amount 
 FROM data
 WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers
 SELECT subscription_status, 
 COUNT(customer_id) as total_customers,
 ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS avg_purchase_amount,
 ROUND(SUM(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS total_revenue
 from data
 group by subscription_status
 order by total_revenue, avg_purchase_amount desc;
 
-- Q6 which 5 products have the highest percentage of purchase with discount applied.
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*),
           2
       ) AS discount_purchase_percentage
FROM data
GROUP BY item_purchased
ORDER BY discount_purchase_percentage DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchase, and show the count of each segment;
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases <= 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM data
)


-- Q8 what are the top 3 most purchased products within each category?
SELECT customer_segment , COUNT(*) as number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM data
    GROUP BY category, item_purchased
),

ranked_items AS (
    SELECT *,
           ROW_NUMBER() OVER(
               PARTITION BY category
               ORDER BY total_orders DESC
           ) AS item_rank
    FROM item_counts
)

SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM ranked_items
WHERE item_rank <= 3;


-- Q9 Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status,
count(customer_id) AS repeat_buyers
FROM data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM data
GROUP BY age_group
ORDER BY total_revenue DESC;

